services:
  postgres:
    image: postgres:16
    container_name: lesson3-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bench
      POSTGRES_USER: bench
      POSTGRES_PASSWORD: bench
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
      - ./data:/data:ro
    command:
      - postgres
      - -c
      - shared_buffers=2GB
      - -c
      - max_connections=200
      - -c
      - work_mem=256MB
      - -c
      - effective_cache_size=6GB
      - -c
      - maintenance_work_mem=512MB
      - -c
      - synchronous_commit=on
      - -c
      - wal_level=logical
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bench -d bench"]
      interval: 3s
      timeout: 2s
      retries: 10

volumes:
  pgdata:
